language: go
before_install:
- sudo add-apt-repository ppa:masterminds/glide -y
- sudo apt-get update -q
- sudo apt-get install glide -y
install:
- go get -t ./...
before_deploy:
- make cross-build
- make dist
deploy:
  provider: releases
  api_key:
    secure: aHgkiqcVuGoVOUZtZ2lUv8Erm7IZzg9qH2op+Sv6AEMXQKX+6QjbQIVVIRjR21M/ME1/GagZDgIikbLa11Ts0SqoxE65HqAO2Phkv8QPolD3PMMVq7zFGaUNn0FzeWEsQZz4+Q/anlhd/0c0HK6N0LuKq8IfKbc/udmSGFgRgvA2iLqdWVT5Qtvopz8xx7gQKsPj8BVvDDKfBuEoV+2auGfeeCc7UJCFtDjqMKBDkQgRIVJY/tYhEMpn7pR6KSp7cYgv7KWPjPw9jrDLDqLk73rDov6z3S29TsrOw9osunPp9iDSKAL65KfhyDPAy+DtqeDQgeTc6q33ATa4wCKQM75NhAE8srnEv6TVd41CnChAtus5WoU+hqRMUYm7itms71o6lkLhq6DDP3y6Nn1qfUes/SBUmi5U4Jnt/sYvGpehMxzRu4LUy1TR8g550GmBrG6kpZoGkfjmbd/K8YMIJvCcV52wKZ2izX9AZxRYzTJ7mDFgxhJbucFCYpE6UiDTSZsHUO+WvSUgypwj6Do6Vo8qyau4ouWvM/JU9IcnyuB+WtZG6bhw68fxC5mHYE0iYPXTfojcUtHKLrV4fL9iqtr+ohfblArmMwyxAW5YXxElCLQY8kYWu39VKsPrvdUITXM8VM1RbuYQSMCKOkwMfrTxweOyefZWY/PIFF2S9XA=
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: dist/*.{tar.gz}
  on:
    repo: tzmfreedom/goroon
    tags: true
after_deploy:
- make release
env:
  global:
  - secure: rq3QseYeXUUiGBNpcRMQolpf3YHDDZWyO3ag3+FjAvPdLnDEX0wIwHwyvDBAEU3x/Byi7SCQp6qKls/M0Luegn17U/hQbTw8L2elFwE2P3iQ0wDgLGWMgJQE3BsqytPG160UEvjN8Xbyy/kc0GxncV6CiCRp0RGiHCY2SDIQM6oaHCb/Co1GdhHgflrSijx7szSUYtCuKyLOSEp4mhqgWs5WwhPiZoQTqjLuElW98Xx9wCLkpw8SJjWkb478Dp0Jlcw1g1JGwoZtlepa34Cpa5yDfc7QTA8/LF/Y/sd9cEzCB4jbJh2Sllp1xYqfCk1DDuLcSqSXSWKRimzTD0ioohQAo4J58eBgg468X91W80nDAXbjuP5z138jBi7Wz8xurFDt/xDNSaopzdQ0sCTiIzC8DLEsl3hDhW3WSpCbWhnE0uX8hji4sI9VLYH1YeBhwrL6xEg1c3aZ3D0/c0T1kWcGfrpuEbO+dZ6CsNWO/DqAUi3xnfhXQbv9GIqQSOgbHSzhQpkAFU/GuEUVFmWmkC/CarmwBU13tnmAjqjCEN8mNjurRD6KJvS9NKOHhdLqwzC9W5WPs29T0vbwPa+3Rb+8KaTVCMcZO0M6S1FgGdpUAhXA7e/28ubWZCj/IZEKESeDc2om2kl2dvAOGoOjoYdvpEwkSC7NYOWTKvgC9bI=
